name: tio
version: '3.2'
summary: A serial device I/O tool
description: >
  tio is a serial device tool which features a straightforward commandline and
  configuration file interface to easily connect to TTY devices for basic I/O
  operations.

base: core20
grade: stable
confinement: classic

apps:
  tio:
    command: usr/bin/tio
    completer: usr/share/bash-completion/completions/tio

parts:
  tio:
    plugin: meson
    source: https://github.com/tio/tio.git
    # source-tag: v2.2
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - pkg-config
      - cmake
      - bash-completion
      - liblua5.2-dev
      - libglib2.0-dev
    stage-packages:
      - bash-completion
      - liblua5.2-0
      - libglib2.0-0
